### ISSUE TITLE
Not an Issue - Just a Message

### ISSUE THREAD

**Issue by Jaliborc** [ButlerLogic/action-autotag#3]
Hey, just opening an issue to send you a message. Autotag has been working great on my node projects, but I handle mostly non-node ones.

So I forked and modified autotag to run on different package structures based on configuration: https://github.com/Jaliborc/action-general-autotag. The license is MIT, but still, thought it was polite to let you know.

**Comment by coreybutler** [comment]
That's pretty cool. I definitely see value in abstracting the file/version the way you've done. Any interest in merging that here?

I'd be interested in setting some defaults so users can use either approach. It also seems like the community would benefit from a list of common RegEx patterns (in the README) in order to customize quickly.

**Comment by Jaliborc** [comment]
Sure. I made a pull request. Do go trough the .json and .yml files though, because I went trough them to set the names of packages/repos to the original ones, but I could have  missed something.

The README file has a couple of patterns in there in the examples but yes, adding a list of common ones would be great. I just wrote the thing because I needed it, so didn't bother going trough that.

**Comment by coreybutler** [comment]
I'll review the JSON/YML and let you know if I see anything. Really appreciate your effort!
