### ISSUE TITLE
When a tag is created, it won't trigger `on push tags` Github actions

### ISSUE THREAD

**Issue by baptisteArno** [ButlerLogic/action-autotag#30]
**Issue:**
Whenever a tag is created using this action, it won't trigger my other actions that uses "On push tags" trigger. These actions work fine when I manually push the tag

**How To Reproduce:**
1. Create a GH action that starts with:
```
on:
  push:
    tags:
      - 'v*.*.*'
```
2. Create a tag from the `action-autotag` action
3. The action from step 1 won't be triggered

**Comment by coreybutler** [comment]
You have to use a personal access token instead of the Github token to do this. See [Triggering a Workflow from a Workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow:~:text=If%20you%20do%20want%20to%20trigger%20a%20workflow%20from%20within%20a%20workflow%20run%2C%20you%20can%20use%20a%20personal%20access%20token%20instead%20of%20GITHUB_TOKEN%20to%20trigger%20events%20that%20require%20a%20token.).
